HEAD:
  mixed-port: 7890
  allow-lan: true
  bind-address: "*"
  log-level: warning
  external-controller: 0.0.0.0:9090
  ipv6: false
  disable-keep-alive: false
  profile:
  store-selected: true
  dns:
    enable: true
    listen: 0.0.0.0:1053
    ipv6: false
    enhanced-mode: fake-ip
    fake-ip-range: 28.0.0.1/8
    fake-ip-filter-mode: blacklist
    fake-ip-filter:
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - "time1.cloud.tencent.com"
    - "*.lan"
    default-nameserver:
    - 223.5.5.5
    nameserver:
    - 223.5.5.5
    - 119.29.29.29
TEST_URL: https://www.gstatic.com/generate_204
RULESET:
- - 全球直连
  - https://raw.githubusercontent.com/MatoGropetrends/clash-custom-rules/refs/heads/main/custom-cn.list
- - Gemini
  - https://raw.githubusercontent.com/MatoGropetrends/clash-custom-rules/refs/heads/main/gemini.list
- - Genflow
  - https://raw.githubusercontent.com/MatoGropetrends/clash-custom-rules/refs/heads/main/genflow-server.list
- - Anthropic
  - https://raw.githubusercontent.com/MatoGropetrends/clash-custom-rules/refs/heads/main/anthropic.list
- - AdsPower|ipcidr
  - https://raw.githubusercontent.com/MatoGropetrends/clash-custom-rules/refs/heads/main/adspower-proxies.mrs
- - 全球直连|domain
  - https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs
- - Apple|domain
  - https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple.mrs
- - ChatGPT|domain
  - https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-ai-!cn.mrs
- - Netflix|domain
  - https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs
- - GitHub|domain
  - https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs
- - YouTube|domain
  - https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs
- - Google|domain
  - https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs
- - Telegram|domain
  - https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs
- - 全球直连|domain
  - https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs
- - Google|ipcidr
  - https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs
- - Telegram|ipcidr
  - https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs
- - 全球直连|ipcidr
  - https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs
- - 全球直连
  - '[]GEOIP,CN'
- - 漏网之鱼
  - '[]FINAL'
CUSTOM_PROXY_GROUP:
- name: 套餐信息
  type: select
  rule: false
  regex: 剩余|到期|续费
- name: 自动选择
  type: url-test
  rule: false
- name: 手动切换
  type: select
  manual: true
  rule: false
- name: 手动切换2
  type: select
  manual: true
  rule: false
- name: 手动切换-Gemini
  type: select
  manual: true
  rule: false
- name: 手动切换-ChatGPT
  type: select
  manual: true
  rule: false
- name: 手动切换-Netflix
  type: select
  manual: true
  rule: false
- name: 手动切换-Genflow
  type: select
  manual: true
  rule: false
- name: Gemini
  type: select
  prior: PROXY
- name: Genflow
  type: select
  prior: PROXY
- name: Anthropic
  type: select
  prior: PROXY
- name: Apple
  type: select
  prior: PROXY
- name: ChatGPT
  type: select
  prior: PROXY
- name: AdsPower
  type: select
  prior: PROXY
- name: Netflix
  type: select
  prior: PROXY
- name: GitHub
  type: select
  prior: PROXY
- name: YouTube
  type: select
  prior: PROXY
- name: Google
  type: select
  prior: PROXY
- name: Telegram
  type: select
  prior: PROXY
- name: 全球直连
  type: select
  prior: DIRECT
- name: 漏网之鱼
  type: select
  prior: PROXY
- name: 🤖 链式代理
  type: select
  rule: false
  regex: ^(?!【仅海外用户】).*(链式代理)
- name: Genflow自动测速节点
  type: url-test
  rule: false
  regex: ^(?!【仅海外用户】).*(日本|新加坡|Vless-US)
- name: 🇭🇰 香港节点
  type: select
  rule: false
  regex: ^(?!【仅海外用户】).*(🇭🇰|HK|Hong|Kong|HGC|WTT|CMI|香港)
- name: 🇨🇳 台湾节点
  type: select
  rule: false
  regex: ^(?!【仅海外用户】).*(TW|Taiwan|新北|彰化|CHT|台湾|HINET)
- name: 🇸🇬 新加坡节点
  type: select
  rule: false
  regex: ^(?!【仅海外用户】).*(🇸🇬|SG|Singapore|新加坡|^新[^节北]|[^刷更]新[^节北])
- name: 🇯🇵 日本节点
  type: select
  rule: false
  regex: ^(?!【仅海外用户】).*(🇯🇵|JP|Japan|Tokyo|Osaka|Saitama|东京|大阪|埼玉|日本)
- name: 🇰🇷 韩国节点
  type: select
  rule: false
  regex: ^(?!【仅海外用户】).*(🇰🇷|KO?R|Korea|首尔|韩|韓)
- name: 🇬🇧 英国节点
  type: select
  rule: false
  regex: ^(?!【仅海外用户】).*(🇬🇧|英国)
- name: 🇺🇸 美国节点
  type: select
  rule: false
  regex: ^(?!【仅海外用户】).*(🇺🇸|US|America|United.*?States|美国|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥)
